name: ci-alpha

on:
  push:
    branches:
      - master
      - bionded
    paths:
      - 'pyproject.toml'
      - 'Dockerfile'
      - 'zspotify/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          echo "version=$(cat pyproject.toml | grep -oP '(?<=version = ")[^"]*')" >> $GITHUB_ENV
          if [[ "${{github.base_ref}}" == "master" ]]; then
            echo "version=${{ env.version }}" >> $GITHUB_ENV
          else
            echo "version=${{ env.version }}-${{ github.base_ref }}" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zspotify:${{ env.VERSION }}-${{ env.BUILD_NUMBER }}
